### PR TITLE
Fix parser

### PR DESCRIPTION
**Pull request by DireLines**

### CODE REVIEW

**Comment by DireLines** [comment]
@pacak made some stuff parse, mostly by removing the `?` inside the macro. I think the parsing doesn't happen correctly for optional groups in some cases because I had to change the rule for `member_assign` to get, for example, `x.y = 5;` to parse. However, now `5 = 6;` will parse even though it doesn't end with an identifier, which is why the original grammar rule was written how it's written

**Comment by pacak** [comment]
Can you add some failing tests? No need to produce exact tokens for expected output, just `todo!()` with a comment of what's expected would do - I'll take a look.

**Comment by DireLines** [comment]
```rust
//TODO: this should parse
#[test]
fn test_parse_member_assign() {
    let sample = "
    x.y = 5;
    ";
    let scanner = Scanner::new(sample);
    let tokens = scanner.collect::<Vec<_>>();
    let x = Program::program(&tokens);
    println!("{:#?}",x);
    todo!("this should parse as an assignment, but it does not parse (leftover tokens)");
}
```
```rust
//TODO: this should not parse
#[test]
fn test_parse_constant_assign_fails() {
    let sample = "
    5 = 6;
    ";
    let scanner = Scanner::new(sample);
    let tokens = scanner.collect::<Vec<_>>();
    let x = Program::program(&tokens);
    println!("{:#?}",x);
    todo!("this should not parse as an assignment");
}
```

**Comment by DireLines** [comment]
The other thing that happened when I got rid of the `?` inside the macro is it changed which lexeme it pointed to in the error cases so they started failing.

**Pull request merged**
